package com.example.demo.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class ShopOrderAssociationPayExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table shop_order_association_pay
     *
     * @mbggenerated Tue May 11 15:55:33 CST 2021
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table shop_order_association_pay
     *
     * @mbggenerated Tue May 11 15:55:33 CST 2021
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table shop_order_association_pay
     *
     * @mbggenerated Tue May 11 15:55:33 CST 2021
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order_association_pay
     *
     * @mbggenerated Tue May 11 15:55:33 CST 2021
     */
    public ShopOrderAssociationPayExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order_association_pay
     *
     * @mbggenerated Tue May 11 15:55:33 CST 2021
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order_association_pay
     *
     * @mbggenerated Tue May 11 15:55:33 CST 2021
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order_association_pay
     *
     * @mbggenerated Tue May 11 15:55:33 CST 2021
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order_association_pay
     *
     * @mbggenerated Tue May 11 15:55:33 CST 2021
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order_association_pay
     *
     * @mbggenerated Tue May 11 15:55:33 CST 2021
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order_association_pay
     *
     * @mbggenerated Tue May 11 15:55:33 CST 2021
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order_association_pay
     *
     * @mbggenerated Tue May 11 15:55:33 CST 2021
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order_association_pay
     *
     * @mbggenerated Tue May 11 15:55:33 CST 2021
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order_association_pay
     *
     * @mbggenerated Tue May 11 15:55:33 CST 2021
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order_association_pay
     *
     * @mbggenerated Tue May 11 15:55:33 CST 2021
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table shop_order_association_pay
     *
     * @mbggenerated Tue May 11 15:55:33 CST 2021
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPaysIdIsNull() {
            addCriterion("pays_id is null");
            return (Criteria) this;
        }

        public Criteria andPaysIdIsNotNull() {
            addCriterion("pays_id is not null");
            return (Criteria) this;
        }

        public Criteria andPaysIdEqualTo(Long value) {
            addCriterion("pays_id =", value, "paysId");
            return (Criteria) this;
        }

        public Criteria andPaysIdNotEqualTo(Long value) {
            addCriterion("pays_id <>", value, "paysId");
            return (Criteria) this;
        }

        public Criteria andPaysIdGreaterThan(Long value) {
            addCriterion("pays_id >", value, "paysId");
            return (Criteria) this;
        }

        public Criteria andPaysIdGreaterThanOrEqualTo(Long value) {
            addCriterion("pays_id >=", value, "paysId");
            return (Criteria) this;
        }

        public Criteria andPaysIdLessThan(Long value) {
            addCriterion("pays_id <", value, "paysId");
            return (Criteria) this;
        }

        public Criteria andPaysIdLessThanOrEqualTo(Long value) {
            addCriterion("pays_id <=", value, "paysId");
            return (Criteria) this;
        }

        public Criteria andPaysIdIn(List<Long> values) {
            addCriterion("pays_id in", values, "paysId");
            return (Criteria) this;
        }

        public Criteria andPaysIdNotIn(List<Long> values) {
            addCriterion("pays_id not in", values, "paysId");
            return (Criteria) this;
        }

        public Criteria andPaysIdBetween(Long value1, Long value2) {
            addCriterion("pays_id between", value1, value2, "paysId");
            return (Criteria) this;
        }

        public Criteria andPaysIdNotBetween(Long value1, Long value2) {
            addCriterion("pays_id not between", value1, value2, "paysId");
            return (Criteria) this;
        }

        public Criteria andSoIdIsNull() {
            addCriterion("so_id is null");
            return (Criteria) this;
        }

        public Criteria andSoIdIsNotNull() {
            addCriterion("so_id is not null");
            return (Criteria) this;
        }

        public Criteria andSoIdEqualTo(String value) {
            addCriterion("so_id =", value, "soId");
            return (Criteria) this;
        }

        public Criteria andSoIdNotEqualTo(String value) {
            addCriterion("so_id <>", value, "soId");
            return (Criteria) this;
        }

        public Criteria andSoIdGreaterThan(String value) {
            addCriterion("so_id >", value, "soId");
            return (Criteria) this;
        }

        public Criteria andSoIdGreaterThanOrEqualTo(String value) {
            addCriterion("so_id >=", value, "soId");
            return (Criteria) this;
        }

        public Criteria andSoIdLessThan(String value) {
            addCriterion("so_id <", value, "soId");
            return (Criteria) this;
        }

        public Criteria andSoIdLessThanOrEqualTo(String value) {
            addCriterion("so_id <=", value, "soId");
            return (Criteria) this;
        }

        public Criteria andSoIdLike(String value) {
            addCriterion("so_id like", value, "soId");
            return (Criteria) this;
        }

        public Criteria andSoIdNotLike(String value) {
            addCriterion("so_id not like", value, "soId");
            return (Criteria) this;
        }

        public Criteria andSoIdIn(List<String> values) {
            addCriterion("so_id in", values, "soId");
            return (Criteria) this;
        }

        public Criteria andSoIdNotIn(List<String> values) {
            addCriterion("so_id not in", values, "soId");
            return (Criteria) this;
        }

        public Criteria andSoIdBetween(String value1, String value2) {
            addCriterion("so_id between", value1, value2, "soId");
            return (Criteria) this;
        }

        public Criteria andSoIdNotBetween(String value1, String value2) {
            addCriterion("so_id not between", value1, value2, "soId");
            return (Criteria) this;
        }

        public Criteria andBuyerAccountIsNull() {
            addCriterion("buyer_account is null");
            return (Criteria) this;
        }

        public Criteria andBuyerAccountIsNotNull() {
            addCriterion("buyer_account is not null");
            return (Criteria) this;
        }

        public Criteria andBuyerAccountEqualTo(String value) {
            addCriterion("buyer_account =", value, "buyerAccount");
            return (Criteria) this;
        }

        public Criteria andBuyerAccountNotEqualTo(String value) {
            addCriterion("buyer_account <>", value, "buyerAccount");
            return (Criteria) this;
        }

        public Criteria andBuyerAccountGreaterThan(String value) {
            addCriterion("buyer_account >", value, "buyerAccount");
            return (Criteria) this;
        }

        public Criteria andBuyerAccountGreaterThanOrEqualTo(String value) {
            addCriterion("buyer_account >=", value, "buyerAccount");
            return (Criteria) this;
        }

        public Criteria andBuyerAccountLessThan(String value) {
            addCriterion("buyer_account <", value, "buyerAccount");
            return (Criteria) this;
        }

        public Criteria andBuyerAccountLessThanOrEqualTo(String value) {
            addCriterion("buyer_account <=", value, "buyerAccount");
            return (Criteria) this;
        }

        public Criteria andBuyerAccountLike(String value) {
            addCriterion("buyer_account like", value, "buyerAccount");
            return (Criteria) this;
        }

        public Criteria andBuyerAccountNotLike(String value) {
            addCriterion("buyer_account not like", value, "buyerAccount");
            return (Criteria) this;
        }

        public Criteria andBuyerAccountIn(List<String> values) {
            addCriterion("buyer_account in", values, "buyerAccount");
            return (Criteria) this;
        }

        public Criteria andBuyerAccountNotIn(List<String> values) {
            addCriterion("buyer_account not in", values, "buyerAccount");
            return (Criteria) this;
        }

        public Criteria andBuyerAccountBetween(String value1, String value2) {
            addCriterion("buyer_account between", value1, value2, "buyerAccount");
            return (Criteria) this;
        }

        public Criteria andBuyerAccountNotBetween(String value1, String value2) {
            addCriterion("buyer_account not between", value1, value2, "buyerAccount");
            return (Criteria) this;
        }

        public Criteria andAmountIsNull() {
            addCriterion("amount is null");
            return (Criteria) this;
        }

        public Criteria andAmountIsNotNull() {
            addCriterion("amount is not null");
            return (Criteria) this;
        }

        public Criteria andAmountEqualTo(BigDecimal value) {
            addCriterion("amount =", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountNotEqualTo(BigDecimal value) {
            addCriterion("amount <>", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountGreaterThan(BigDecimal value) {
            addCriterion("amount >", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("amount >=", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountLessThan(BigDecimal value) {
            addCriterion("amount <", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("amount <=", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountIn(List<BigDecimal> values) {
            addCriterion("amount in", values, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountNotIn(List<BigDecimal> values) {
            addCriterion("amount not in", values, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("amount between", value1, value2, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("amount not between", value1, value2, "amount");
            return (Criteria) this;
        }

        public Criteria andPayDateIsNull() {
            addCriterion("pay_date is null");
            return (Criteria) this;
        }

        public Criteria andPayDateIsNotNull() {
            addCriterion("pay_date is not null");
            return (Criteria) this;
        }

        public Criteria andPayDateEqualTo(String value) {
            addCriterion("pay_date =", value, "payDate");
            return (Criteria) this;
        }

        public Criteria andPayDateNotEqualTo(String value) {
            addCriterion("pay_date <>", value, "payDate");
            return (Criteria) this;
        }

        public Criteria andPayDateGreaterThan(String value) {
            addCriterion("pay_date >", value, "payDate");
            return (Criteria) this;
        }

        public Criteria andPayDateGreaterThanOrEqualTo(String value) {
            addCriterion("pay_date >=", value, "payDate");
            return (Criteria) this;
        }

        public Criteria andPayDateLessThan(String value) {
            addCriterion("pay_date <", value, "payDate");
            return (Criteria) this;
        }

        public Criteria andPayDateLessThanOrEqualTo(String value) {
            addCriterion("pay_date <=", value, "payDate");
            return (Criteria) this;
        }

        public Criteria andPayDateLike(String value) {
            addCriterion("pay_date like", value, "payDate");
            return (Criteria) this;
        }

        public Criteria andPayDateNotLike(String value) {
            addCriterion("pay_date not like", value, "payDate");
            return (Criteria) this;
        }

        public Criteria andPayDateIn(List<String> values) {
            addCriterion("pay_date in", values, "payDate");
            return (Criteria) this;
        }

        public Criteria andPayDateNotIn(List<String> values) {
            addCriterion("pay_date not in", values, "payDate");
            return (Criteria) this;
        }

        public Criteria andPayDateBetween(String value1, String value2) {
            addCriterion("pay_date between", value1, value2, "payDate");
            return (Criteria) this;
        }

        public Criteria andPayDateNotBetween(String value1, String value2) {
            addCriterion("pay_date not between", value1, value2, "payDate");
            return (Criteria) this;
        }

        public Criteria andOuterPayIdIsNull() {
            addCriterion("outer_pay_id is null");
            return (Criteria) this;
        }

        public Criteria andOuterPayIdIsNotNull() {
            addCriterion("outer_pay_id is not null");
            return (Criteria) this;
        }

        public Criteria andOuterPayIdEqualTo(String value) {
            addCriterion("outer_pay_id =", value, "outerPayId");
            return (Criteria) this;
        }

        public Criteria andOuterPayIdNotEqualTo(String value) {
            addCriterion("outer_pay_id <>", value, "outerPayId");
            return (Criteria) this;
        }

        public Criteria andOuterPayIdGreaterThan(String value) {
            addCriterion("outer_pay_id >", value, "outerPayId");
            return (Criteria) this;
        }

        public Criteria andOuterPayIdGreaterThanOrEqualTo(String value) {
            addCriterion("outer_pay_id >=", value, "outerPayId");
            return (Criteria) this;
        }

        public Criteria andOuterPayIdLessThan(String value) {
            addCriterion("outer_pay_id <", value, "outerPayId");
            return (Criteria) this;
        }

        public Criteria andOuterPayIdLessThanOrEqualTo(String value) {
            addCriterion("outer_pay_id <=", value, "outerPayId");
            return (Criteria) this;
        }

        public Criteria andOuterPayIdLike(String value) {
            addCriterion("outer_pay_id like", value, "outerPayId");
            return (Criteria) this;
        }

        public Criteria andOuterPayIdNotLike(String value) {
            addCriterion("outer_pay_id not like", value, "outerPayId");
            return (Criteria) this;
        }

        public Criteria andOuterPayIdIn(List<String> values) {
            addCriterion("outer_pay_id in", values, "outerPayId");
            return (Criteria) this;
        }

        public Criteria andOuterPayIdNotIn(List<String> values) {
            addCriterion("outer_pay_id not in", values, "outerPayId");
            return (Criteria) this;
        }

        public Criteria andOuterPayIdBetween(String value1, String value2) {
            addCriterion("outer_pay_id between", value1, value2, "outerPayId");
            return (Criteria) this;
        }

        public Criteria andOuterPayIdNotBetween(String value1, String value2) {
            addCriterion("outer_pay_id not between", value1, value2, "outerPayId");
            return (Criteria) this;
        }

        public Criteria andPayIdIsNull() {
            addCriterion("pay_id is null");
            return (Criteria) this;
        }

        public Criteria andPayIdIsNotNull() {
            addCriterion("pay_id is not null");
            return (Criteria) this;
        }

        public Criteria andPayIdEqualTo(String value) {
            addCriterion("pay_id =", value, "payId");
            return (Criteria) this;
        }

        public Criteria andPayIdNotEqualTo(String value) {
            addCriterion("pay_id <>", value, "payId");
            return (Criteria) this;
        }

        public Criteria andPayIdGreaterThan(String value) {
            addCriterion("pay_id >", value, "payId");
            return (Criteria) this;
        }

        public Criteria andPayIdGreaterThanOrEqualTo(String value) {
            addCriterion("pay_id >=", value, "payId");
            return (Criteria) this;
        }

        public Criteria andPayIdLessThan(String value) {
            addCriterion("pay_id <", value, "payId");
            return (Criteria) this;
        }

        public Criteria andPayIdLessThanOrEqualTo(String value) {
            addCriterion("pay_id <=", value, "payId");
            return (Criteria) this;
        }

        public Criteria andPayIdLike(String value) {
            addCriterion("pay_id like", value, "payId");
            return (Criteria) this;
        }

        public Criteria andPayIdNotLike(String value) {
            addCriterion("pay_id not like", value, "payId");
            return (Criteria) this;
        }

        public Criteria andPayIdIn(List<String> values) {
            addCriterion("pay_id in", values, "payId");
            return (Criteria) this;
        }

        public Criteria andPayIdNotIn(List<String> values) {
            addCriterion("pay_id not in", values, "payId");
            return (Criteria) this;
        }

        public Criteria andPayIdBetween(String value1, String value2) {
            addCriterion("pay_id between", value1, value2, "payId");
            return (Criteria) this;
        }

        public Criteria andPayIdNotBetween(String value1, String value2) {
            addCriterion("pay_id not between", value1, value2, "payId");
            return (Criteria) this;
        }

        public Criteria andPaymentIsNull() {
            addCriterion("payment is null");
            return (Criteria) this;
        }

        public Criteria andPaymentIsNotNull() {
            addCriterion("payment is not null");
            return (Criteria) this;
        }

        public Criteria andPaymentEqualTo(String value) {
            addCriterion("payment =", value, "payment");
            return (Criteria) this;
        }

        public Criteria andPaymentNotEqualTo(String value) {
            addCriterion("payment <>", value, "payment");
            return (Criteria) this;
        }

        public Criteria andPaymentGreaterThan(String value) {
            addCriterion("payment >", value, "payment");
            return (Criteria) this;
        }

        public Criteria andPaymentGreaterThanOrEqualTo(String value) {
            addCriterion("payment >=", value, "payment");
            return (Criteria) this;
        }

        public Criteria andPaymentLessThan(String value) {
            addCriterion("payment <", value, "payment");
            return (Criteria) this;
        }

        public Criteria andPaymentLessThanOrEqualTo(String value) {
            addCriterion("payment <=", value, "payment");
            return (Criteria) this;
        }

        public Criteria andPaymentLike(String value) {
            addCriterion("payment like", value, "payment");
            return (Criteria) this;
        }

        public Criteria andPaymentNotLike(String value) {
            addCriterion("payment not like", value, "payment");
            return (Criteria) this;
        }

        public Criteria andPaymentIn(List<String> values) {
            addCriterion("payment in", values, "payment");
            return (Criteria) this;
        }

        public Criteria andPaymentNotIn(List<String> values) {
            addCriterion("payment not in", values, "payment");
            return (Criteria) this;
        }

        public Criteria andPaymentBetween(String value1, String value2) {
            addCriterion("payment between", value1, value2, "payment");
            return (Criteria) this;
        }

        public Criteria andPaymentNotBetween(String value1, String value2) {
            addCriterion("payment not between", value1, value2, "payment");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table shop_order_association_pay
     *
     * @mbggenerated do_not_delete_during_merge Tue May 11 15:55:33 CST 2021
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table shop_order_association_pay
     *
     * @mbggenerated Tue May 11 15:55:33 CST 2021
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}