package com.example.demo.entity;

import java.math.BigDecimal;

public class ShopOrderAssociationPay {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_order_association_pay.pays_id
     *
     * @mbggenerated Tue May 11 15:55:33 CST 2021
     */
    private Long paysId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_order_association_pay.so_id
     *
     * @mbggenerated Tue May 11 15:55:33 CST 2021
     */
    private String soId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_order_association_pay.buyer_account
     *
     * @mbggenerated Tue May 11 15:55:33 CST 2021
     */
    private String buyerAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_order_association_pay.amount
     *
     * @mbggenerated Tue May 11 15:55:33 CST 2021
     */
    private BigDecimal amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_order_association_pay.pay_date
     *
     * @mbggenerated Tue May 11 15:55:33 CST 2021
     */
    private String payDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_order_association_pay.outer_pay_id
     *
     * @mbggenerated Tue May 11 15:55:33 CST 2021
     */
    private String outerPayId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_order_association_pay.pay_id
     *
     * @mbggenerated Tue May 11 15:55:33 CST 2021
     */
    private String payId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_order_association_pay.payment
     *
     * @mbggenerated Tue May 11 15:55:33 CST 2021
     */
    private String payment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_order_association_pay.pays_id
     *
     * @return the value of shop_order_association_pay.pays_id
     *
     * @mbggenerated Tue May 11 15:55:33 CST 2021
     */
    public Long getPaysId() {
        return paysId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_order_association_pay.pays_id
     *
     * @param paysId the value for shop_order_association_pay.pays_id
     *
     * @mbggenerated Tue May 11 15:55:33 CST 2021
     */
    public void setPaysId(Long paysId) {
        this.paysId = paysId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_order_association_pay.so_id
     *
     * @return the value of shop_order_association_pay.so_id
     *
     * @mbggenerated Tue May 11 15:55:33 CST 2021
     */
    public String getSoId() {
        return soId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_order_association_pay.so_id
     *
     * @param soId the value for shop_order_association_pay.so_id
     *
     * @mbggenerated Tue May 11 15:55:33 CST 2021
     */
    public void setSoId(String soId) {
        this.soId = soId == null ? null : soId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_order_association_pay.buyer_account
     *
     * @return the value of shop_order_association_pay.buyer_account
     *
     * @mbggenerated Tue May 11 15:55:33 CST 2021
     */
    public String getBuyerAccount() {
        return buyerAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_order_association_pay.buyer_account
     *
     * @param buyerAccount the value for shop_order_association_pay.buyer_account
     *
     * @mbggenerated Tue May 11 15:55:33 CST 2021
     */
    public void setBuyerAccount(String buyerAccount) {
        this.buyerAccount = buyerAccount == null ? null : buyerAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_order_association_pay.amount
     *
     * @return the value of shop_order_association_pay.amount
     *
     * @mbggenerated Tue May 11 15:55:33 CST 2021
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_order_association_pay.amount
     *
     * @param amount the value for shop_order_association_pay.amount
     *
     * @mbggenerated Tue May 11 15:55:33 CST 2021
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_order_association_pay.pay_date
     *
     * @return the value of shop_order_association_pay.pay_date
     *
     * @mbggenerated Tue May 11 15:55:33 CST 2021
     */
    public String getPayDate() {
        return payDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_order_association_pay.pay_date
     *
     * @param payDate the value for shop_order_association_pay.pay_date
     *
     * @mbggenerated Tue May 11 15:55:33 CST 2021
     */
    public void setPayDate(String payDate) {
        this.payDate = payDate == null ? null : payDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_order_association_pay.outer_pay_id
     *
     * @return the value of shop_order_association_pay.outer_pay_id
     *
     * @mbggenerated Tue May 11 15:55:33 CST 2021
     */
    public String getOuterPayId() {
        return outerPayId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_order_association_pay.outer_pay_id
     *
     * @param outerPayId the value for shop_order_association_pay.outer_pay_id
     *
     * @mbggenerated Tue May 11 15:55:33 CST 2021
     */
    public void setOuterPayId(String outerPayId) {
        this.outerPayId = outerPayId == null ? null : outerPayId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_order_association_pay.pay_id
     *
     * @return the value of shop_order_association_pay.pay_id
     *
     * @mbggenerated Tue May 11 15:55:33 CST 2021
     */
    public String getPayId() {
        return payId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_order_association_pay.pay_id
     *
     * @param payId the value for shop_order_association_pay.pay_id
     *
     * @mbggenerated Tue May 11 15:55:33 CST 2021
     */
    public void setPayId(String payId) {
        this.payId = payId == null ? null : payId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_order_association_pay.payment
     *
     * @return the value of shop_order_association_pay.payment
     *
     * @mbggenerated Tue May 11 15:55:33 CST 2021
     */
    public String getPayment() {
        return payment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_order_association_pay.payment
     *
     * @param payment the value for shop_order_association_pay.payment
     *
     * @mbggenerated Tue May 11 15:55:33 CST 2021
     */
    public void setPayment(String payment) {
        this.payment = payment == null ? null : payment.trim();
    }
}