package com.example.demo.entity;

public class ShopOrderAssociation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_order_association.association_id
     *
     * @mbggenerated Tue May 11 15:54:47 CST 2021
     */
    private Long associationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_order_association.l_id
     *
     * @mbggenerated Tue May 11 15:54:47 CST 2021
     */
    private String lId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_order_association.send_date
     *
     * @mbggenerated Tue May 11 15:54:47 CST 2021
     */
    private String sendDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_order_association.pay_date
     *
     * @mbggenerated Tue May 11 15:54:47 CST 2021
     */
    private String payDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_order_association.receiver_address
     *
     * @mbggenerated Tue May 11 15:54:47 CST 2021
     */
    private String receiverAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_order_association.receiver_district
     *
     * @mbggenerated Tue May 11 15:54:47 CST 2021
     */
    private String receiverDistrict;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_order_association.wms_co_id
     *
     * @mbggenerated Tue May 11 15:54:47 CST 2021
     */
    private String wmsCoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_order_association.logistics_company
     *
     * @mbggenerated Tue May 11 15:54:47 CST 2021
     */
    private String logisticsCompany;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_order_association.shop_name
     *
     * @mbggenerated Tue May 11 15:54:47 CST 2021
     */
    private String shopName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_order_association.outer_pay_id
     *
     * @mbggenerated Tue May 11 15:54:47 CST 2021
     */
    private String outerPayId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_order_association.so_id
     *
     * @mbggenerated Tue May 11 15:54:47 CST 2021
     */
    private String soId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_order_association.status
     *
     * @mbggenerated Tue May 11 15:54:47 CST 2021
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_order_association.pay_amount
     *
     * @mbggenerated Tue May 11 15:54:47 CST 2021
     */
    private String payAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_order_association.shop_buyer_id
     *
     * @mbggenerated Tue May 11 15:54:47 CST 2021
     */
    private String shopBuyerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_order_association.receiver_mobile
     *
     * @mbggenerated Tue May 11 15:54:47 CST 2021
     */
    private String receiverMobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_order_association.order_date
     *
     * @mbggenerated Tue May 11 15:54:47 CST 2021
     */
    private String orderDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_order_association.receiver_city
     *
     * @mbggenerated Tue May 11 15:54:47 CST 2021
     */
    private String receiverCity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_order_association.receiver_state
     *
     * @mbggenerated Tue May 11 15:54:47 CST 2021
     */
    private String receiverState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_order_association.receiver_town
     *
     * @mbggenerated Tue May 11 15:54:47 CST 2021
     */
    private String receiverTown;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_order_association.receiver_name
     *
     * @mbggenerated Tue May 11 15:54:47 CST 2021
     */
    private String receiverName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_order_association.o_id
     *
     * @mbggenerated Tue May 11 15:54:47 CST 2021
     */
    private Integer oId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_order_association.shop_id
     *
     * @mbggenerated Tue May 11 15:54:47 CST 2021
     */
    private Integer shopId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_order_association.paid_amount
     *
     * @mbggenerated Tue May 11 15:54:47 CST 2021
     */
    private String paidAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_order_association.currency
     *
     * @mbggenerated Tue May 11 15:54:47 CST 2021
     */
    private String currency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_order_association.is_deleted
     *
     * @mbggenerated Tue May 11 15:54:47 CST 2021
     */
    private Boolean isDeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_order_association.association_id
     *
     * @return the value of shop_order_association.association_id
     *
     * @mbggenerated Tue May 11 15:54:47 CST 2021
     */
    public Long getAssociationId() {
        return associationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_order_association.association_id
     *
     * @param associationId the value for shop_order_association.association_id
     *
     * @mbggenerated Tue May 11 15:54:47 CST 2021
     */
    public void setAssociationId(Long associationId) {
        this.associationId = associationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_order_association.l_id
     *
     * @return the value of shop_order_association.l_id
     *
     * @mbggenerated Tue May 11 15:54:47 CST 2021
     */
    public String getlId() {
        return lId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_order_association.l_id
     *
     * @param lId the value for shop_order_association.l_id
     *
     * @mbggenerated Tue May 11 15:54:47 CST 2021
     */
    public void setlId(String lId) {
        this.lId = lId == null ? null : lId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_order_association.send_date
     *
     * @return the value of shop_order_association.send_date
     *
     * @mbggenerated Tue May 11 15:54:47 CST 2021
     */
    public String getSendDate() {
        return sendDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_order_association.send_date
     *
     * @param sendDate the value for shop_order_association.send_date
     *
     * @mbggenerated Tue May 11 15:54:47 CST 2021
     */
    public void setSendDate(String sendDate) {
        this.sendDate = sendDate == null ? null : sendDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_order_association.pay_date
     *
     * @return the value of shop_order_association.pay_date
     *
     * @mbggenerated Tue May 11 15:54:47 CST 2021
     */
    public String getPayDate() {
        return payDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_order_association.pay_date
     *
     * @param payDate the value for shop_order_association.pay_date
     *
     * @mbggenerated Tue May 11 15:54:47 CST 2021
     */
    public void setPayDate(String payDate) {
        this.payDate = payDate == null ? null : payDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_order_association.receiver_address
     *
     * @return the value of shop_order_association.receiver_address
     *
     * @mbggenerated Tue May 11 15:54:47 CST 2021
     */
    public String getReceiverAddress() {
        return receiverAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_order_association.receiver_address
     *
     * @param receiverAddress the value for shop_order_association.receiver_address
     *
     * @mbggenerated Tue May 11 15:54:47 CST 2021
     */
    public void setReceiverAddress(String receiverAddress) {
        this.receiverAddress = receiverAddress == null ? null : receiverAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_order_association.receiver_district
     *
     * @return the value of shop_order_association.receiver_district
     *
     * @mbggenerated Tue May 11 15:54:47 CST 2021
     */
    public String getReceiverDistrict() {
        return receiverDistrict;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_order_association.receiver_district
     *
     * @param receiverDistrict the value for shop_order_association.receiver_district
     *
     * @mbggenerated Tue May 11 15:54:47 CST 2021
     */
    public void setReceiverDistrict(String receiverDistrict) {
        this.receiverDistrict = receiverDistrict == null ? null : receiverDistrict.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_order_association.wms_co_id
     *
     * @return the value of shop_order_association.wms_co_id
     *
     * @mbggenerated Tue May 11 15:54:47 CST 2021
     */
    public String getWmsCoId() {
        return wmsCoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_order_association.wms_co_id
     *
     * @param wmsCoId the value for shop_order_association.wms_co_id
     *
     * @mbggenerated Tue May 11 15:54:47 CST 2021
     */
    public void setWmsCoId(String wmsCoId) {
        this.wmsCoId = wmsCoId == null ? null : wmsCoId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_order_association.logistics_company
     *
     * @return the value of shop_order_association.logistics_company
     *
     * @mbggenerated Tue May 11 15:54:47 CST 2021
     */
    public String getLogisticsCompany() {
        return logisticsCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_order_association.logistics_company
     *
     * @param logisticsCompany the value for shop_order_association.logistics_company
     *
     * @mbggenerated Tue May 11 15:54:47 CST 2021
     */
    public void setLogisticsCompany(String logisticsCompany) {
        this.logisticsCompany = logisticsCompany == null ? null : logisticsCompany.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_order_association.shop_name
     *
     * @return the value of shop_order_association.shop_name
     *
     * @mbggenerated Tue May 11 15:54:47 CST 2021
     */
    public String getShopName() {
        return shopName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_order_association.shop_name
     *
     * @param shopName the value for shop_order_association.shop_name
     *
     * @mbggenerated Tue May 11 15:54:47 CST 2021
     */
    public void setShopName(String shopName) {
        this.shopName = shopName == null ? null : shopName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_order_association.outer_pay_id
     *
     * @return the value of shop_order_association.outer_pay_id
     *
     * @mbggenerated Tue May 11 15:54:47 CST 2021
     */
    public String getOuterPayId() {
        return outerPayId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_order_association.outer_pay_id
     *
     * @param outerPayId the value for shop_order_association.outer_pay_id
     *
     * @mbggenerated Tue May 11 15:54:47 CST 2021
     */
    public void setOuterPayId(String outerPayId) {
        this.outerPayId = outerPayId == null ? null : outerPayId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_order_association.so_id
     *
     * @return the value of shop_order_association.so_id
     *
     * @mbggenerated Tue May 11 15:54:47 CST 2021
     */
    public String getSoId() {
        return soId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_order_association.so_id
     *
     * @param soId the value for shop_order_association.so_id
     *
     * @mbggenerated Tue May 11 15:54:47 CST 2021
     */
    public void setSoId(String soId) {
        this.soId = soId == null ? null : soId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_order_association.status
     *
     * @return the value of shop_order_association.status
     *
     * @mbggenerated Tue May 11 15:54:47 CST 2021
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_order_association.status
     *
     * @param status the value for shop_order_association.status
     *
     * @mbggenerated Tue May 11 15:54:47 CST 2021
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_order_association.pay_amount
     *
     * @return the value of shop_order_association.pay_amount
     *
     * @mbggenerated Tue May 11 15:54:47 CST 2021
     */
    public String getPayAmount() {
        return payAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_order_association.pay_amount
     *
     * @param payAmount the value for shop_order_association.pay_amount
     *
     * @mbggenerated Tue May 11 15:54:47 CST 2021
     */
    public void setPayAmount(String payAmount) {
        this.payAmount = payAmount == null ? null : payAmount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_order_association.shop_buyer_id
     *
     * @return the value of shop_order_association.shop_buyer_id
     *
     * @mbggenerated Tue May 11 15:54:47 CST 2021
     */
    public String getShopBuyerId() {
        return shopBuyerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_order_association.shop_buyer_id
     *
     * @param shopBuyerId the value for shop_order_association.shop_buyer_id
     *
     * @mbggenerated Tue May 11 15:54:47 CST 2021
     */
    public void setShopBuyerId(String shopBuyerId) {
        this.shopBuyerId = shopBuyerId == null ? null : shopBuyerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_order_association.receiver_mobile
     *
     * @return the value of shop_order_association.receiver_mobile
     *
     * @mbggenerated Tue May 11 15:54:47 CST 2021
     */
    public String getReceiverMobile() {
        return receiverMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_order_association.receiver_mobile
     *
     * @param receiverMobile the value for shop_order_association.receiver_mobile
     *
     * @mbggenerated Tue May 11 15:54:47 CST 2021
     */
    public void setReceiverMobile(String receiverMobile) {
        this.receiverMobile = receiverMobile == null ? null : receiverMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_order_association.order_date
     *
     * @return the value of shop_order_association.order_date
     *
     * @mbggenerated Tue May 11 15:54:47 CST 2021
     */
    public String getOrderDate() {
        return orderDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_order_association.order_date
     *
     * @param orderDate the value for shop_order_association.order_date
     *
     * @mbggenerated Tue May 11 15:54:47 CST 2021
     */
    public void setOrderDate(String orderDate) {
        this.orderDate = orderDate == null ? null : orderDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_order_association.receiver_city
     *
     * @return the value of shop_order_association.receiver_city
     *
     * @mbggenerated Tue May 11 15:54:47 CST 2021
     */
    public String getReceiverCity() {
        return receiverCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_order_association.receiver_city
     *
     * @param receiverCity the value for shop_order_association.receiver_city
     *
     * @mbggenerated Tue May 11 15:54:47 CST 2021
     */
    public void setReceiverCity(String receiverCity) {
        this.receiverCity = receiverCity == null ? null : receiverCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_order_association.receiver_state
     *
     * @return the value of shop_order_association.receiver_state
     *
     * @mbggenerated Tue May 11 15:54:47 CST 2021
     */
    public String getReceiverState() {
        return receiverState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_order_association.receiver_state
     *
     * @param receiverState the value for shop_order_association.receiver_state
     *
     * @mbggenerated Tue May 11 15:54:47 CST 2021
     */
    public void setReceiverState(String receiverState) {
        this.receiverState = receiverState == null ? null : receiverState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_order_association.receiver_town
     *
     * @return the value of shop_order_association.receiver_town
     *
     * @mbggenerated Tue May 11 15:54:47 CST 2021
     */
    public String getReceiverTown() {
        return receiverTown;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_order_association.receiver_town
     *
     * @param receiverTown the value for shop_order_association.receiver_town
     *
     * @mbggenerated Tue May 11 15:54:47 CST 2021
     */
    public void setReceiverTown(String receiverTown) {
        this.receiverTown = receiverTown == null ? null : receiverTown.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_order_association.receiver_name
     *
     * @return the value of shop_order_association.receiver_name
     *
     * @mbggenerated Tue May 11 15:54:47 CST 2021
     */
    public String getReceiverName() {
        return receiverName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_order_association.receiver_name
     *
     * @param receiverName the value for shop_order_association.receiver_name
     *
     * @mbggenerated Tue May 11 15:54:47 CST 2021
     */
    public void setReceiverName(String receiverName) {
        this.receiverName = receiverName == null ? null : receiverName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_order_association.o_id
     *
     * @return the value of shop_order_association.o_id
     *
     * @mbggenerated Tue May 11 15:54:47 CST 2021
     */
    public Integer getoId() {
        return oId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_order_association.o_id
     *
     * @param oId the value for shop_order_association.o_id
     *
     * @mbggenerated Tue May 11 15:54:47 CST 2021
     */
    public void setoId(Integer oId) {
        this.oId = oId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_order_association.shop_id
     *
     * @return the value of shop_order_association.shop_id
     *
     * @mbggenerated Tue May 11 15:54:47 CST 2021
     */
    public Integer getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_order_association.shop_id
     *
     * @param shopId the value for shop_order_association.shop_id
     *
     * @mbggenerated Tue May 11 15:54:47 CST 2021
     */
    public void setShopId(Integer shopId) {
        this.shopId = shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_order_association.paid_amount
     *
     * @return the value of shop_order_association.paid_amount
     *
     * @mbggenerated Tue May 11 15:54:47 CST 2021
     */
    public String getPaidAmount() {
        return paidAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_order_association.paid_amount
     *
     * @param paidAmount the value for shop_order_association.paid_amount
     *
     * @mbggenerated Tue May 11 15:54:47 CST 2021
     */
    public void setPaidAmount(String paidAmount) {
        this.paidAmount = paidAmount == null ? null : paidAmount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_order_association.currency
     *
     * @return the value of shop_order_association.currency
     *
     * @mbggenerated Tue May 11 15:54:47 CST 2021
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_order_association.currency
     *
     * @param currency the value for shop_order_association.currency
     *
     * @mbggenerated Tue May 11 15:54:47 CST 2021
     */
    public void setCurrency(String currency) {
        this.currency = currency == null ? null : currency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_order_association.is_deleted
     *
     * @return the value of shop_order_association.is_deleted
     *
     * @mbggenerated Tue May 11 15:54:47 CST 2021
     */
    public Boolean getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_order_association.is_deleted
     *
     * @param isDeleted the value for shop_order_association.is_deleted
     *
     * @mbggenerated Tue May 11 15:54:47 CST 2021
     */
    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }
}