package com.example.demo.entity;

public class ShopOrderAssociationGoods {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_order_association_goods.goods_id
     *
     * @mbggenerated Tue May 11 15:55:11 CST 2021
     */
    private Long goodsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_order_association_goods.sku_id
     *
     * @mbggenerated Tue May 11 15:55:11 CST 2021
     */
    private String skuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_order_association_goods.name
     *
     * @mbggenerated Tue May 11 15:55:11 CST 2021
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_order_association_goods.refund_status
     *
     * @mbggenerated Tue May 11 15:55:11 CST 2021
     */
    private String refundStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_order_association_goods.price
     *
     * @mbggenerated Tue May 11 15:55:11 CST 2021
     */
    private String price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_order_association_goods.qty
     *
     * @mbggenerated Tue May 11 15:55:11 CST 2021
     */
    private Integer qty;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_order_association_goods.goods_id
     *
     * @return the value of shop_order_association_goods.goods_id
     *
     * @mbggenerated Tue May 11 15:55:11 CST 2021
     */
    public Long getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_order_association_goods.goods_id
     *
     * @param goodsId the value for shop_order_association_goods.goods_id
     *
     * @mbggenerated Tue May 11 15:55:11 CST 2021
     */
    public void setGoodsId(Long goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_order_association_goods.sku_id
     *
     * @return the value of shop_order_association_goods.sku_id
     *
     * @mbggenerated Tue May 11 15:55:11 CST 2021
     */
    public String getSkuId() {
        return skuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_order_association_goods.sku_id
     *
     * @param skuId the value for shop_order_association_goods.sku_id
     *
     * @mbggenerated Tue May 11 15:55:11 CST 2021
     */
    public void setSkuId(String skuId) {
        this.skuId = skuId == null ? null : skuId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_order_association_goods.name
     *
     * @return the value of shop_order_association_goods.name
     *
     * @mbggenerated Tue May 11 15:55:11 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_order_association_goods.name
     *
     * @param name the value for shop_order_association_goods.name
     *
     * @mbggenerated Tue May 11 15:55:11 CST 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_order_association_goods.refund_status
     *
     * @return the value of shop_order_association_goods.refund_status
     *
     * @mbggenerated Tue May 11 15:55:11 CST 2021
     */
    public String getRefundStatus() {
        return refundStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_order_association_goods.refund_status
     *
     * @param refundStatus the value for shop_order_association_goods.refund_status
     *
     * @mbggenerated Tue May 11 15:55:11 CST 2021
     */
    public void setRefundStatus(String refundStatus) {
        this.refundStatus = refundStatus == null ? null : refundStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_order_association_goods.price
     *
     * @return the value of shop_order_association_goods.price
     *
     * @mbggenerated Tue May 11 15:55:11 CST 2021
     */
    public String getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_order_association_goods.price
     *
     * @param price the value for shop_order_association_goods.price
     *
     * @mbggenerated Tue May 11 15:55:11 CST 2021
     */
    public void setPrice(String price) {
        this.price = price == null ? null : price.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_order_association_goods.qty
     *
     * @return the value of shop_order_association_goods.qty
     *
     * @mbggenerated Tue May 11 15:55:11 CST 2021
     */
    public Integer getQty() {
        return qty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_order_association_goods.qty
     *
     * @param qty the value for shop_order_association_goods.qty
     *
     * @mbggenerated Tue May 11 15:55:11 CST 2021
     */
    public void setQty(Integer qty) {
        this.qty = qty;
    }
}