package com.example.demo.entity;

import java.util.Date;

public class SysUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.id
     *
     * @mbggenerated Sat Mar 13 22:05:17 CST 2021
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.user_num
     *
     * @mbggenerated Sat Mar 13 22:05:17 CST 2021
     */
    private String userNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.org_code
     *
     * @mbggenerated Sat Mar 13 22:05:17 CST 2021
     */
    private String orgCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.status
     *
     * @mbggenerated Sat Mar 13 22:05:17 CST 2021
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.last_loging_time
     *
     * @mbggenerated Sat Mar 13 22:05:17 CST 2021
     */
    private Date lastLogingTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.delete_flag
     *
     * @mbggenerated Sat Mar 13 22:05:17 CST 2021
     */
    private String deleteFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.onclick
     *
     * @mbggenerated Sat Mar 13 22:05:17 CST 2021
     */
    private String onclick;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.create_time
     *
     * @mbggenerated Sat Mar 13 22:05:17 CST 2021
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.create_code
     *
     * @mbggenerated Sat Mar 13 22:05:17 CST 2021
     */
    private String createCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.update_time
     *
     * @mbggenerated Sat Mar 13 22:05:17 CST 2021
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.update_code
     *
     * @mbggenerated Sat Mar 13 22:05:17 CST 2021
     */
    private String updateCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.id
     *
     * @return the value of sys_user.id
     *
     * @mbggenerated Sat Mar 13 22:05:17 CST 2021
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.id
     *
     * @param id the value for sys_user.id
     *
     * @mbggenerated Sat Mar 13 22:05:17 CST 2021
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.user_num
     *
     * @return the value of sys_user.user_num
     *
     * @mbggenerated Sat Mar 13 22:05:17 CST 2021
     */
    public String getUserNum() {
        return userNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.user_num
     *
     * @param userNum the value for sys_user.user_num
     *
     * @mbggenerated Sat Mar 13 22:05:17 CST 2021
     */
    public void setUserNum(String userNum) {
        this.userNum = userNum == null ? null : userNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.org_code
     *
     * @return the value of sys_user.org_code
     *
     * @mbggenerated Sat Mar 13 22:05:17 CST 2021
     */
    public String getOrgCode() {
        return orgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.org_code
     *
     * @param orgCode the value for sys_user.org_code
     *
     * @mbggenerated Sat Mar 13 22:05:17 CST 2021
     */
    public void setOrgCode(String orgCode) {
        this.orgCode = orgCode == null ? null : orgCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.status
     *
     * @return the value of sys_user.status
     *
     * @mbggenerated Sat Mar 13 22:05:17 CST 2021
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.status
     *
     * @param status the value for sys_user.status
     *
     * @mbggenerated Sat Mar 13 22:05:17 CST 2021
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.last_loging_time
     *
     * @return the value of sys_user.last_loging_time
     *
     * @mbggenerated Sat Mar 13 22:05:17 CST 2021
     */
    public Date getLastLogingTime() {
        return lastLogingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.last_loging_time
     *
     * @param lastLogingTime the value for sys_user.last_loging_time
     *
     * @mbggenerated Sat Mar 13 22:05:17 CST 2021
     */
    public void setLastLogingTime(Date lastLogingTime) {
        this.lastLogingTime = lastLogingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.delete_flag
     *
     * @return the value of sys_user.delete_flag
     *
     * @mbggenerated Sat Mar 13 22:05:17 CST 2021
     */
    public String getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.delete_flag
     *
     * @param deleteFlag the value for sys_user.delete_flag
     *
     * @mbggenerated Sat Mar 13 22:05:17 CST 2021
     */
    public void setDeleteFlag(String deleteFlag) {
        this.deleteFlag = deleteFlag == null ? null : deleteFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.onclick
     *
     * @return the value of sys_user.onclick
     *
     * @mbggenerated Sat Mar 13 22:05:17 CST 2021
     */
    public String getOnclick() {
        return onclick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.onclick
     *
     * @param onclick the value for sys_user.onclick
     *
     * @mbggenerated Sat Mar 13 22:05:17 CST 2021
     */
    public void setOnclick(String onclick) {
        this.onclick = onclick == null ? null : onclick.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.create_time
     *
     * @return the value of sys_user.create_time
     *
     * @mbggenerated Sat Mar 13 22:05:17 CST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.create_time
     *
     * @param createTime the value for sys_user.create_time
     *
     * @mbggenerated Sat Mar 13 22:05:17 CST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.create_code
     *
     * @return the value of sys_user.create_code
     *
     * @mbggenerated Sat Mar 13 22:05:17 CST 2021
     */
    public String getCreateCode() {
        return createCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.create_code
     *
     * @param createCode the value for sys_user.create_code
     *
     * @mbggenerated Sat Mar 13 22:05:17 CST 2021
     */
    public void setCreateCode(String createCode) {
        this.createCode = createCode == null ? null : createCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.update_time
     *
     * @return the value of sys_user.update_time
     *
     * @mbggenerated Sat Mar 13 22:05:17 CST 2021
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.update_time
     *
     * @param updateTime the value for sys_user.update_time
     *
     * @mbggenerated Sat Mar 13 22:05:17 CST 2021
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.update_code
     *
     * @return the value of sys_user.update_code
     *
     * @mbggenerated Sat Mar 13 22:05:17 CST 2021
     */
    public String getUpdateCode() {
        return updateCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.update_code
     *
     * @param updateCode the value for sys_user.update_code
     *
     * @mbggenerated Sat Mar 13 22:05:17 CST 2021
     */
    public void setUpdateCode(String updateCode) {
        this.updateCode = updateCode == null ? null : updateCode.trim();
    }
}