package com.example.demo.mapper;

import com.example.demo.entity.ShopOrderAssociationPay;
import com.example.demo.entity.ShopOrderAssociationPayExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ShopOrderAssociationPayMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order_association_pay
     *
     * @mbggenerated Tue May 11 15:55:33 CST 2021
     */
    int countByExample(ShopOrderAssociationPayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order_association_pay
     *
     * @mbggenerated Tue May 11 15:55:33 CST 2021
     */
    int deleteByExample(ShopOrderAssociationPayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order_association_pay
     *
     * @mbggenerated Tue May 11 15:55:33 CST 2021
     */
    int deleteByPrimaryKey(Long paysId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order_association_pay
     *
     * @mbggenerated Tue May 11 15:55:33 CST 2021
     */
    int insert(ShopOrderAssociationPay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order_association_pay
     *
     * @mbggenerated Tue May 11 15:55:33 CST 2021
     */
    int insertSelective(ShopOrderAssociationPay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order_association_pay
     *
     * @mbggenerated Tue May 11 15:55:33 CST 2021
     */
    List<ShopOrderAssociationPay> selectByExample(ShopOrderAssociationPayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order_association_pay
     *
     * @mbggenerated Tue May 11 15:55:33 CST 2021
     */
    ShopOrderAssociationPay selectByPrimaryKey(Long paysId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order_association_pay
     *
     * @mbggenerated Tue May 11 15:55:33 CST 2021
     */
    int updateByExampleSelective(@Param("record") ShopOrderAssociationPay record, @Param("example") ShopOrderAssociationPayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order_association_pay
     *
     * @mbggenerated Tue May 11 15:55:33 CST 2021
     */
    int updateByExample(@Param("record") ShopOrderAssociationPay record, @Param("example") ShopOrderAssociationPayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order_association_pay
     *
     * @mbggenerated Tue May 11 15:55:33 CST 2021
     */
    int updateByPrimaryKeySelective(ShopOrderAssociationPay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order_association_pay
     *
     * @mbggenerated Tue May 11 15:55:33 CST 2021
     */
    int updateByPrimaryKey(ShopOrderAssociationPay record);
}