package com.example.demo.mapper;

import com.example.demo.entity.SysUser;
import com.example.demo.entity.SysUserExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface SysUserMapper {
    Integer saveShopOrderAssociation(@Param("mapList") List<Map<String,Object>> mapList);
    /**
     * 根据唯一主键查询他
     * @param soIdList 主键集合
     * @return 查询到了哪些是有的，最好查不到。
     */
    List<String> findShopOrderAssociationNumberBySoId(@Param("soIdList") List<String>soIdList);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Sat Mar 13 22:05:17 CST 2021
     */

    int countByExample(SysUserExample example);

    Integer insertStores( @Param("paramMap") List<Map<String,Object>> paramMap);

    Map<String,Object> queryAssociation(Map<String,Object> paramMap);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Sat Mar 13 22:05:17 CST 2021
     */
    int deleteByExample(SysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Sat Mar 13 22:05:17 CST 2021
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Sat Mar 13 22:05:17 CST 2021
     */
    int insert(SysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Sat Mar 13 22:05:17 CST 2021
     */
    int insertSelective(SysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Sat Mar 13 22:05:17 CST 2021
     */
    List<SysUser> selectByExample(SysUserExample example);

    List<Map<String,Object>> queryAny(Map<String,Object> example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Sat Mar 13 22:05:17 CST 2021
     */
    SysUser selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Sat Mar 13 22:05:17 CST 2021
     */
    int updateByExampleSelective(@Param("record") SysUser record, @Param("example") SysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Sat Mar 13 22:05:17 CST 2021
     */
    int updateByExample(@Param("record") SysUser record, @Param("example") SysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Sat Mar 13 22:05:17 CST 2021
     */
    int updateByPrimaryKeySelective(SysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Sat Mar 13 22:05:17 CST 2021
     */
    int updateByPrimaryKey(SysUser record);
}